name: Playwright CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # pull everything from repository and give to runner

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Install Playwright browsers + deps
        run: npx playwright install --with-deps

      - name: Install Allure dependencies
        run: |
          npm install -D allure-playwright allure-commandline

      # Run tests with Playwright HTML + Allure reporter
      - name: Run Playwright tests
        run: npx playwright test --reporter=line,allure-playwright,html

      # Debug to confirm allure results exist
      - name: Debug allure results
        run: ls -R ./allure-results || echo "No allure results found"

      # Generate Allure HTML report
      - name: Generate Allure report
        run: npx allure-commandline generate ./allure-results --clean -o ./allure-report

      # Upload Allure HTML report
      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/

      # Upload Playwright HTML report
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
