name: Playwright CI - quick

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Install Playwright browsers + deps
        run: npx playwright install --with-deps

      - name: Install Allure dependencies
        run: |
          npm install -D allure-playwright allure-commandline

      - name: Run Playwright tests with Allure reporter
        run: npx playwright test --reporter=line,allure-playwright

      - name: Generate Allure report
        run: npx allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports\allure-results

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
